# Generated by Django 3.1.13 on 2021-08-28 13:51

import cuser.fields
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_auto_20210601_2122'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0020_contratovenda_itemcontratovenda_revisaocontratovenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemFornecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_format_ano', models.CharField(blank=True, max_length=10, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.revisaocontratocompra')),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ordemfornecimento', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'ativo': True, 'tipo': 'OF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.status')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_ordemfornecimento', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'verbose_name': 'Ordem de Fornecimento',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemOF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('ord_item', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Item')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('diaria', models.IntegerField(blank=True, null=True)),
                ('valor_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Valor unitário')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itemof', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('ordem_fornecimento', models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='controle_eventos.ordemfornecimento')),
                ('produto', models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='contratos.itemcontratocompra')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_itemof', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'ordering': ['ord_item'],
            },
        ),
    ]
