# Generated by Django 3.1.13 on 2021-08-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0020_contratovenda_itemcontratovenda_revisaocontratovenda'),
        ('controle_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemfornecimento',
            name='contrato',
            field=models.ForeignKey(limit_choices_to={'is_vigente': True}, on_delete=django.db.models.deletion.PROTECT, to='contratos.revisaocontratocompra'),
        ),
    ]
