# Generated by Django 3.1.13 on 2021-08-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_eventos', '0002_auto_20210828_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemof',
            name='is_contabilizado',
            field=models.BooleanField(default=False),
        ),
    ]
