# Generated by Django 3.1.13 on 2021-08-31 22:04

import cuser.fields
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controle_eventos', '0003_itemof_is_contabilizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemof',
            name='is_contabilizado',
        ),
        migrations.RemoveField(
            model_name='itemof',
            name='valor_unit',
        ),
        migrations.AddField(
            model_name='itemof',
            name='fim_desmontagem',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemof',
            name='inicio_montagem',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DecomposicaoValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('valor_corrigido', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Valor corrigido')),
                ('diaria_inicial', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diaria_final', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Subtotal')),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_decomposicaovalor', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_eventos.itemof')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_decomposicaovalor', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
