# Generated by Django 3.1.13 on 2021-08-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_eventos', '0004_auto_20210831_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decomposicaovalor',
            name='diaria_final',
        ),
        migrations.RemoveField(
            model_name='decomposicaovalor',
            name='diaria_inicial',
        ),
        migrations.AddField(
            model_name='decomposicaovalor',
            name='dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
