# Generated by Django 3.1.13 on 2021-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_eventos', '0005_auto_20210831_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='decomposicaovalor',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
