# Generated by Django 3.1.13 on 2021-09-02 21:17

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0023_auto_20210902_1615'),
        ('controle_eventos', '0006_decomposicaovalor_desconto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubItemOF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subitemof', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('item_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.subitemcontratocompra')),
                ('item_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_eventos.itemof')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_subitemof', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
