# Generated by Django 3.1.13 on 2021-09-02 23:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_eventos', '0007_subitemof'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemof',
            name='quantidade_anterior',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AddField(
            model_name='itemof',
            name='valor_total_anterior',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
    ]
