# Generated by Django 3.1.11 on 2021-06-04 14:56

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210601_2122'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='data_gco',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='numero_edital',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='refer_sistema',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='sistema',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='status',
        ),
        migrations.CreateModel(
            name='ProcessoCompra',
            fields=[
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('processo_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='processo_compra', serialize=False, to='processos.processo')),
                ('numero_edital', models.CharField(blank=True, max_length=12, null=True)),
                ('refer_sistema', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Referência no Sistema')),
                ('data_gco', models.DateField(blank=True, null=True, verbose_name='Recebido na GCO em:')),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_processocompra', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('modalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.modalidade')),
                ('sistema', models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.sistema')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'LC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.status')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_processocompra', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
