# Generated by Django 3.1.11 on 2021-06-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20210606_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processocompra',
            options={'ordering': ['-data_gco']},
        ),
    ]
