# Generated by Django 3.1.11 on 2021-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_auto_20210607_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Objeto'),
        ),
    ]
