# Generated by Django 3.1.11 on 2021-06-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_auto_20210616_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidade',
            name='fundamento',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='sigla',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='processo',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Objeto'),
        ),
        migrations.AlterField(
            model_name='processocompra',
            name='numero_edital',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='processocompra',
            name='refer_sistema',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Referência no Sistema'),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='descricao',
            field=models.CharField(max_length=30),
        ),
    ]
