# Generated by Django 3.1.13 on 2021-09-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_contato'),
        ('processos', '0006_processocompra_subgrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processocompra',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, to='empresa.Departamento'),
        ),
        migrations.AddField(
            model_name='processocompra',
            name='comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.funcionario'),
        ),
    ]
