# Generated by Django 3.1.13 on 2021-09-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_contato'),
        ('processos', '0007_auto_20210925_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processocompra',
            name='area',
            field=models.ManyToManyField(to='empresa.Departamento'),
        ),
    ]
