# Generated by Django 3.1.13 on 2021-10-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_auto_20210925_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processocompra',
            name='numero_edital',
        ),
        migrations.RemoveField(
            model_name='processocompra',
            name='refer_sistema',
        ),
    ]
