# Generated by Django 3.1.13 on 2021-10-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210601_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='contabiliza_saldo',
            field=models.BooleanField(default=True),
        ),
    ]
