# Generated by Django 3.1.11 on 2021-05-27 03:06

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classeproduto', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_classeproduto', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'verbose_name': 'Classe de Objeto',
                'verbose_name_plural': 'Classes de Objeto',
            },
        ),
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('classe', models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.PROTECT, to='produtos.classeproduto')),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grupoproduto', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_grupoproduto', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'verbose_name': 'Grupo de Objeto',
                'verbose_name_plural': 'Grupos de Objeto',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='SubGrupoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('classe', models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.PROTECT, to='produtos.classeproduto')),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subgrupoproduto', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('grupo', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='classe', chained_model_field='classe', limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.CASCADE, to='produtos.grupoproduto')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_subgrupoproduto', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'verbose_name': 'Subgrupo de Objeto',
                'verbose_name_plural': 'Subgrupos de Objeto',
                'ordering': ['classe', 'grupo', 'descricao'],
            },
        ),
    ]
