# Generated by Django 3.1.11 on 2021-05-27 03:31

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('descricao', models.CharField(max_length=200, unique=True, verbose_name='Descrição')),
                ('sigla', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('especifica', models.TextField(blank=True, max_length=1000, null=True)),
                ('numprotheus', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('ultimoprecocompra', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('tabela_eventos', models.BooleanField(default=False)),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_produto', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('subgrupo', models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_subgrupo', to='produtos.subgrupoproduto')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_produto', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unidademedida', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_unidademedida', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='SubProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('fator', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tipofator', models.CharField(blank=True, choices=[('Acréscimo', 'Acréscimo'), ('Desconto', 'Desconto')], max_length=9, null=True)),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subproduto', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('produto', models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='subproduto_produto', to='produtos.produto')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_subproduto', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'verbose_name': 'Subproduto',
                'verbose_name_plural': 'Subprodutos',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.unidademedida'),
        ),
    ]
