# Generated by Django 3.1.11 on 2021-06-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20210527_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ultimoprecocompra',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, verbose_name='Último Preço de Compra'),
        ),
    ]
