# Generated by Django 3.1.11 on 2021-06-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20210619_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['descricao'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
