# Generated by Django 3.1.11 on 2021-06-06 17:27

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocompra',
            name='processo',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processo'),
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='ultimo_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_solicitacaocompra', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:'),
        ),
        migrations.AddField(
            model_name='itemsc',
            name='criador',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itemsc', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:'),
        ),
        migrations.AddField(
            model_name='itemsc',
            name='produto',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemsc_produto', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='itemsc',
            name='solicitacao',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsc_sc', to='compras.solicitacaocompra'),
        ),
        migrations.AddField(
            model_name='itemsc',
            name='subgrupo',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemsc_subgrupo', to='produtos.subgrupoproduto'),
        ),
        migrations.AddField(
            model_name='itemsc',
            name='ultimo_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_itemsc', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:'),
        ),
    ]
