# Generated by Django 3.1.11 on 2021-06-01 06:00

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsc',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemsc',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:'),
        ),
        migrations.AddField(
            model_name='itemsc',
            name='criador',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itemsc', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:'),
        ),
        migrations.AddField(
            model_name='itemsc',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:'),
        ),
        migrations.AddField(
            model_name='itemsc',
            name='ultimo_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_itemsc', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:'),
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:'),
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='criador',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_solicitacaocompra', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:'),
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:'),
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='ultimo_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_solicitacaocompra', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:'),
        ),
    ]
