# Generated by Django 3.1.11 on 2021-06-07 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_auto_20210607_1342'),
        ('compras', '0002_auto_20210606_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='processo',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sc_processo', to='processos.processo'),
        ),
    ]
