# Generated by Django 3.1.11 on 2021-06-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20210607_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsc',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='objeto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
