# Generated by Django 3.1.11 on 2021-06-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20210618_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsc',
            name='solicitacao',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.solicitacaocompra'),
        ),
    ]
