# Generated by Django 3.1.11 on 2021-06-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20210614_1609'),
        ('compras', '0006_auto_20210620_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocompra',
            name='area',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.departamento'),
        ),
    ]
