# Generated by Django 3.1.11 on 2021-06-21 22:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_centrocusto_contacontabil'),
        ('compras', '0008_auto_20210621_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsc',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='itemsc',
            name='ord_item',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemsc',
            name='valor_unit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Valor unitário'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='area',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.departamento', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='centro_custo',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.centrocusto', verbose_name='Centro de Custo'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='conta_contabil',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.contacontabil', verbose_name='Conta Contábil'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Emitida em'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.funcionario', verbose_name='Responsável'),
        ),
    ]
