# Generated by Django 3.1.11 on 2021-06-21 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_auto_20210621_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsc',
            options={'ordering': ['ord_item'], 'verbose_name': 'Item da Solicitação de Compras', 'verbose_name_plural': 'Itens da Solicitação de Compras'},
        ),
    ]
