# Generated by Django 3.1.11 on 2021-06-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_auto_20210621_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaocompra',
            options={'ordering': ['numsc'], 'verbose_name': 'Solicitação de Compras', 'verbose_name_plural': 'Solicitações de Compras'},
        ),
    ]
