# Generated by Django 3.1.13 on 2021-10-12 00:15

import cuser.fields
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20210621_1445'),
        ('processos', '0009_auto_20211011_1831'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20210601_2122'),
        ('compras', '0012_auto_20210622_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('refer_sistema', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Referência no Sistema')),
                ('numero_edital', models.CharField(blank=True, max_length=20, null=True)),
                ('data_disputa', models.DateTimeField(blank=True, null=True)),
                ('valor_arrematado', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('valor_adjudicado', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pregao', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.processocompra')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'ativo': True, 'tipo': 'LC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.status')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_pregao', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('numero', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lote', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('pregao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.pregao')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_lote', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('ord_item', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Item')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('valor_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Valor unitário')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itemlote', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.lote')),
                ('produto', models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_itemlote', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
