# Generated by Django 3.1.13 on 2021-10-25 20:08

import cuser.fields
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20210621_1445'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0015_itemproposta_pesquisa_proposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproposta',
            name='produto',
        ),
        migrations.AddField(
            model_name='itemproposta',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AddField(
            model_name='itemproposta',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AddField(
            model_name='itemproposta',
            name='valor_unit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Valor unitário'),
        ),
        migrations.CreateModel(
            name='ItemPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('ord_item', models.CharField(blank=True, max_length=4, null=True, verbose_name='Item')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('valor_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Valor unitário')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itempesquisa', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.pesquisa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_itempesquisa', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='itemproposta',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compras.itempesquisa'),
            preserve_default=False,
        ),
    ]
