# Generated by Django 3.1.13 on 2021-08-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosof',
            name='empenho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sof.empenho'),
        ),
        migrations.AlterField(
            model_name='contratosof',
            name='reserva',
            field=models.ManyToManyField(blank=True, null=True, to='sof.Reserva'),
        ),
    ]
