# Generated by Django 3.1.13 on 2021-08-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sof', '0002_auto_20210815_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosof',
            name='reserva',
            field=models.ManyToManyField(blank=True, to='sof.Reserva'),
        ),
    ]
