# Generated by Django 3.1.13 on 2021-08-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_auto_20210815_1832'),
        ('processos', '0005_auto_20210618_1920'),
        ('sof', '0003_auto_20210815_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dotacao',
            options={'ordering': ['funcao', 'subfuncao'], 'verbose_name': 'Dotação Orçamentária', 'verbose_name_plural': 'Dotações Orçamentárias'},
        ),
        migrations.RemoveField(
            model_name='contratosof',
            name='empenho',
        ),
        migrations.RemoveField(
            model_name='contratosof',
            name='reserva',
        ),
        migrations.AddField(
            model_name='contratosof',
            name='contrato_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contratocompra'),
        ),
        migrations.AddField(
            model_name='empenho',
            name='contrato_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contratocompra'),
        ),
        migrations.AddField(
            model_name='empenho',
            name='contrato_sof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sof.contratosof'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='contrato_real',
            field=models.ManyToManyField(blank=True, to='contratos.ContratoCompra'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='processo',
            field=models.ManyToManyField(blank=True, to='processos.Processo'),
        ),
    ]
