# Generated by Django 3.1.11 on 2021-06-28 21:12

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0005_auto_20210618_1920'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0013_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('tipo', models.CharField(choices=[('CCO', 'Substitutivo Contratual'), ('CCN', 'Termo Contratual')], max_length=3)),
                ('subtipo', models.CharField(choices=[('AS', 'Autorização de Serviço'), ('OC', 'Ordem de Compra')], max_length=2)),
                ('numero', models.CharField(max_length=9)),
                ('versao', models.CharField(max_length=3)),
                ('objeto', models.CharField(max_length=500)),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_ini', models.DateField(blank=True, null=True, verbose_name='Início da Vigência')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim da Vigência')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('area', models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.departamento')),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contratocompra', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('fiscal', models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscais', to='empresa.funcionario')),
                ('gestor', models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestores', to='empresa.funcionario')),
                ('processo', models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.processocompra')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_contratocompra', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'ordering': ['tipo', 'numero'],
            },
        ),
    ]
