# Generated by Django 3.1.11 on 2021-06-29 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_contato'),
        ('contratos', '0002_auto_20210628_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratocompra',
            options={'ordering': ['tipo', 'data_assinatura', 'numero']},
        ),
        migrations.AddField(
            model_name='contratocompra',
            name='fornecedor',
            field=models.ForeignKey(default=1, limit_choices_to={'fornecedor': True}, on_delete=django.db.models.deletion.PROTECT, to='empresa.pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contratocompra',
            name='subtipo',
            field=models.CharField(blank=True, choices=[('AS', 'Autorização de Serviço'), ('OC', 'Ordem de Compra')], max_length=2, null=True),
        ),
    ]
