# Generated by Django 3.1.11 on 2021-07-16 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210601_2122'),
        ('contratos', '0006_auto_20210715_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratocompra',
            options={'ordering': ['tipo', 'numero', 'data_assinatura'], 'verbose_name': 'Contrato de Compras', 'verbose_name_plural': 'Contratos de Compras'},
        ),
        migrations.AlterField(
            model_name='contratocompra',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True, 'tipo': 'CC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.status'),
        ),
    ]
