# Generated by Django 3.1.11 on 2021-07-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_auto_20210715_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratocompra',
            options={'ordering': ['tipo', 'data_assinatura', 'numero'], 'verbose_name': 'Contrato de Compras', 'verbose_name_plural': 'Contratos de Compras'},
        ),
    ]
