# Generated by Django 3.1.11 on 2021-07-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_auto_20210715_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisaocontratocompra',
            name='numero',
        ),
        migrations.AddField(
            model_name='revisaocontratocompra',
            name='numero_aditamento',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
