# Generated by Django 3.1.11 on 2021-07-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_auto_20210715_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revisaocontratocompra',
            options={'ordering': ['contrato', 'ordem']},
        ),
        migrations.AddField(
            model_name='revisaocontratocompra',
            name='is_vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcontratocompra',
            name='ord_item',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Item'),
        ),
    ]
