# Generated by Django 3.1.11 on 2021-07-25 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_contato'),
        ('contratos', '0011_auto_20210715_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocompra',
            name='area',
        ),
        migrations.RemoveField(
            model_name='contratocompra',
            name='objeto',
        ),
        migrations.AddField(
            model_name='revisaocontratocompra',
            name='area',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.departamento'),
        ),
        migrations.AddField(
            model_name='revisaocontratocompra',
            name='objeto',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
