# Generated by Django 3.1.11 on 2021-07-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_auto_20210725_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocompra',
            name='numero_format_ano',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='contratocompra',
            name='data_assinatura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Assinatura'),
        ),
    ]
