# Generated by Django 3.1.11 on 2021-08-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_contratocompra_data_entrega_notificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocompra',
            name='data_entrega_notificacao',
        ),
    ]
