# Generated by Django 3.1.13 on 2021-08-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sof', '0002_auto_20210815_1725'),
        ('contratos', '0016_auto_20210815_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocompra',
            name='empenho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sof.empenho'),
        ),
        migrations.AddField(
            model_name='contratocompra',
            name='referencia_sof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='sof.contratosof'),
        ),
        migrations.AddField(
            model_name='contratocompra',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sof.reserva'),
        ),
    ]
