# Generated by Django 3.1.13 on 2021-08-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0017_auto_20210815_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocompra',
            name='empenho',
        ),
        migrations.RemoveField(
            model_name='contratocompra',
            name='referencia_sof',
        ),
        migrations.RemoveField(
            model_name='contratocompra',
            name='reserva',
        ),
    ]
