# Generated by Django 3.1.13 on 2021-08-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0020_contratovenda_itemcontratovenda_revisaocontratovenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisaocontratocompra',
            name='nome_simplificado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='revisaocontratocompra',
            name='objeto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
