# Generated by Django 3.1.13 on 2021-08-30 20:15

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0021_auto_20210828_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubItemContratoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('fator', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tipofator', models.CharField(blank=True, choices=[('Acréscimo', 'Acréscimo'), ('Desconto', 'Desconto')], max_length=9, null=True)),
                ('diaria_inicial', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subitemcontratocompra', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.itemcontratocompra')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_subitemcontratocompra', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
