# Generated by Django 3.1.13 on 2021-09-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_subitemcontratocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitemcontratocompra',
            name='tipofator',
            field=models.CharField(blank=True, choices=[('ACRS', 'Acréscimo'), ('DESC', 'Desconto sobre diária'), ('SUPR', 'Desconto sobre equipamento')], max_length=9, null=True),
        ),
    ]
