# Generated by Django 3.1.13 on 2021-09-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0023_auto_20210902_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocompra',
            name='controle_de_saldo',
            field=models.CharField(choices=[('FIN', 'Financeiro'), ('FIS', 'Físico')], default='FIN', max_length=3),
        ),
    ]
