# Generated by Django 3.1.13 on 2021-10-12 00:15

import cuser.fields
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20210601_2122'),
        ('produtos', '0005_auto_20210621_1445'),
        ('empresa', '0014_funcionario_pregoeiro'),
        ('processos', '0009_auto_20211011_1831'),
        ('contratos', '0025_revisaocontratocompra_subgrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtaRP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('numero', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numero_format_ano', models.CharField(blank=True, max_length=9, null=True)),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_atarp', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('fornecedor', models.ForeignKey(limit_choices_to={'fornecedor': True}, on_delete=django.db.models.deletion.PROTECT, to='empresa.pessoa')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processocompra')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'ativo': True, 'tipo': 'AP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.status')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_atarp', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'verbose_name': 'Ata de Registro de Preços',
                'verbose_name_plural': 'Atas de Registro de Preços',
                'ordering': ['data_assinatura', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemAta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('ord_item', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Item')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('diaria', models.IntegerField(blank=True, null=True)),
                ('valor_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Valor unitário')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('saldo_fis', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Saldo Físico')),
                ('saldo_fin', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Saldo financeiro')),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itemata', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('produto', models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
            options={
                'ordering': ['ord_item'],
            },
        ),
        migrations.CreateModel(
            name='SubItemAta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('fator', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tipofator', models.CharField(blank=True, choices=[('ACRS', 'Acréscimo'), ('DESC', 'Desconto sobre diária'), ('SUPR', 'Desconto sobre equipamento')], max_length=9, null=True)),
                ('diaria_inicial', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subitemata', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.itemata')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_subitemata', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevisaoAta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('numero_aditamento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nome_simplificado', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto', models.CharField(blank=True, max_length=500, null=True)),
                ('ordem', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=1000, null=True)),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_ini', models.DateField(blank=True, null=True, verbose_name='Início da Vigência')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim da Vigência')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('is_vigente', models.BooleanField(default=True)),
                ('cod_protheus', models.CharField(blank=True, max_length=15, null=True)),
                ('data_protheus', models.DateField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.departamento')),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='contratos.atarp')),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revisaoata', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('fiscal', models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscais_da_ata', to='empresa.funcionario')),
                ('gestor', models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestores_da_ata', to='empresa.funcionario')),
                ('subgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.subgrupoproduto')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_revisaoata', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
            ],
            options={
                'ordering': ['ata', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='itemata',
            name='revisao',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.revisaoata'),
        ),
        migrations.AddField(
            model_name='itemata',
            name='ultimo_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_itemata', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:'),
        ),
    ]
