# Generated by Django 3.1.11 on 2021-06-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20210614_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['diretoria', 'gerencia', 'coordenadoria']},
        ),
    ]
