# Generated by Django 3.1.11 on 2021-06-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_pessoa_pessoafisica_pessoajuridica'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='fornecedor',
            field=models.BooleanField(default=False),
        ),
    ]
